# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2SNXHaENa-umbSKd1YHRJy_gm9JqmsY
"""

!pip install langchain-core==0.3.72
!pip install langchain-openai==0.3.28
!pip install langchain-community==0.3.27
!pip install unstructured==0.18.11
!pip install langchain-chroma==0.2.5
!pip install langchain-text-splitters==0.3.9
!pip install pydantic==2.11.9

from langchain_core.prompts import ChatPromptTemplate

from langchain_openai import ChatOpenAI, OpenAIEmbeddings

from langchain_community.document_loaders import UnstructuredHTMLLoader

from langchain_core.runnables import RunnablePassthrough

from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_chroma import Chroma

# Load the HTML as a LangChain document loader
loader = UnstructuredHTMLLoader(file_path="/content/sample_data/Samsung LEVANT.html.html")
machine_docs = loader.load()

import os

os.environ["OPENAI_API_KEY"] = "open AI key"

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

embeddings = OpenAIEmbeddings(model="text-embedding-3-small", openai_api_key=os.environ["OPENAI_API_KEY"])

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
embeddings = OpenAIEmbeddings(model="text-embedding-3-small", openai_api_key=os.environ["OPENAI_API_KEY"])

# Initialize RecursiveCharacterTextSplitter to make chunks of HTML text
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)

# Split the machine documents with text_splitter
splits = text_splitter.split_documents(machine_docs)

# Initialize Chroma vectorstore with documents as splits and using OpenAIEmbeddings
vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings)

retriever = vectorstore.as_retriever()

# Define RAG prompt
prompt = ChatPromptTemplate.from_template("""You are an assistant for question-answering tasks.
Use the following pieces of retrieved context to answer the question.
If you don't know the answer, just say that you don't know.
Use three sentences maximum and keep the answer concise.\nQuestion: {question} \nContext: {context} \nAnswer:""")

rag_chain = (
    {"context": retriever , "question": RunnablePassthrough()}
    | prompt
    | llm
)

# Initialize query
query = "What is the cycle for DRUM CLEAN?"
# Invoke the query
answer = rag_chain.invoke(query).content
print(answer)

# Initialize query
query = "What should I do for DAILY WASH?"

# Invoke the query
answer = rag_chain.invoke(query).content
print(answer)

"""For DAILY WASH, select the cycle on your washing machine designed for everyday items like underwear and shirts. Make sure to use an appropriate amount of detergent, typically less than 20 g for powder or 20 ml for liquid. Follow the machine's instructions to start the cycle"""
